@baseUrl =http://localhost:5050

###########################################################
# AUTH
###########################################################

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username":"idowu",
    "email":"faith@test.com",
    "password":"password123"
}

###

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email":"faith@test.com",
    "password":"password123"
}

###

### Protected Route
GET {{baseUrl}}/api/auth/protected

###

### Logout
POST {{baseUrl}}/api/auth/logout

###########################################################
# MOVIES (TMDB)
###########################################################

### Search Movies
GET {{baseUrl}}/api/media/movie/search?query=Interstellar

###

### Popular Movies
GET {{baseUrl}}/api/media/movie/popular

###

### Trending Movies
GET {{baseUrl}}/api/media/movie/trending

###

### Movie Recommendations
GET {{baseUrl}}/api/media/movie/recommendations?id=157336

###

### Movie Details
GET {{baseUrl}}/api/media/movie/157336

###########################################################
# TV
###########################################################

### Search TV
GET {{baseUrl}}/api/media/tv/search?query=Breaking Bad

###

### Trending TV
GET {{baseUrl}}/api/media/tv/trending

###

### Popular TV
GET {{baseUrl}}/api/media/tv/popular

###

### TV Recommendations
GET {{baseUrl}}/api/media/tv/recommendations?id=1396

###

### TV Details
GET {{baseUrl}}/api/media/tv/1396

###########################################################
# ANIME
###########################################################

### Search Anime
GET {{baseUrl}}/api/media/anime/search?query=Naruto

###

### Top Anime
GET {{baseUrl}}/api/media/anime/top


###

### Current Season
GET {{baseUrl}}/api/media/anime/season/current

###

### Upcoming Season
GET {{baseUrl}}/api/media/anime/season/upcoming

###

### Anime Details
GET {{baseUrl}}/api/media/anime/20

###########################################################
# MANGA
###########################################################

### Search Manga
GET {{baseUrl}}/api/media/manga/search?query=Berserk

###

### Top Manga
GET {{baseUrl}}/api/media/manga/top

###


### Manga Details
GET {{baseUrl}}/api/media/manga/dc332d04-d3b0-413c-a767-70f5e451b031

###########################################################
# BOOKS
###########################################################

### Search Books
GET {{baseUrl}}/api/media/book/search?query=flower

###

### Popular Books
GET {{baseUrl}}/api/media/book/popular

###

### Recommended Books
GET {{baseUrl}}/api/media/book/recommendations

###

### Book Details
GET {{baseUrl}}/api/media/book/OL134834W

###########################################################
# GLOBAL MEDIA SEARCH
###########################################################

### Search Everything
GET {{baseUrl}}/api/media/search?query=One Piece

#############################################################
# MEDIA CONTROLLER
#############################################################

### Dashboard
GET {{baseUrl}}/api/media/dashboard

###

### Get User Shelf
GET {{baseUrl}}/api/media/shelf

###

### Get One Shelf Item
GET {{baseUrl}}/api/media/shelf/e5e6865c-f8a3-4f6a-8512-386a6daef7e2

###

### Add Media To Shelf
POST {{baseUrl}}/api/media/shelf
Content-Type: application/json

{
    "media_type": "movie",
    "external_source": "tmdb",
    "external_id": "157336",
    "title": "Interstellar",
    "creator": "Christopher Nolan",
    "cover_url": "https://image.tmdb.org/t/p/w500/example.jpg",
    "release_year": 2014,
    "genres": [
        "Science Fiction",
        "Adventure"
    ]
}

###

### Update User Log
PUT {{baseUrl}}/api/media/shelf/e5e6865c-f8a3-4f6a-8512-386a6daef7e2
Content-Type: application/json

{
    "status": "completed",
    "rating": 5,
    "review": "One of the best movies I've ever watched.",
    "started_at": "2026-07-01",
    "completed_at": "2026-07-15"
}

###

### Update Status Only
PUT {{baseUrl}}/api/media/shelf/e5e6865c-f8a3-4f6a-8512-386a6daef7e2
Content-Type: application/json

{
    "status": "in_progress"
}

###

### Update Rating Only
PUT {{baseUrl}}/api/media/shelf/e5e6865c-f8a3-4f6a-8512-386a6daef7e2
Content-Type: application/json

{
    "rating": 4
}

###

### Update Review Only
PUT {{baseUrl}}/api/media/shelf/e5e6865c-f8a3-4f6a-8512-386a6daef7e2
Content-Type: application/json

{
    "review": "Great story with amazing visuals."
}

###

### Delete Shelf Item
DELETE {{baseUrl}}/api/media/shelf/e5e6865c-f8a3-4f6a-8512-386a6daef7e2
